Pick n Buy/Controllers/TaylorController.cs
using OTM.BLL;
using OTM.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OTM.Controllers
{
    [Authorize]
    public class TaylorController : Controller
    {
        // GET: Taylor
        public ActionResult Taylor()
        {
            try
            {
                BLL_Taylor obj = new BLL_Taylor();
                List<MdlTaylor> mdlist = obj.BLL_ReadTaylor(Convert.ToInt32(Session["UserID"]));
                return View(mdlist);
            }
            catch (Exception)
            {

                throw;
            }

        }

        public ActionResult AddTaylor()
        {
                return View();
        }
        [HttpPost]
        public ActionResult AddTaylor(MdlTaylor mdl, IEnumerable<HttpPostedFileBase> files)
        {
            try
            {
                var allowedextention = new[] { ".jpg", ".Jpg", ".jpeg", ".png" };
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        var ext = Path.GetExtension(file.FileName);
                        if (allowedextention.Contains(ext))
                        {
                            var filename = Path.GetFileName(file.FileName);
                            var path = "~/images/Taylor_Images/" + filename;
                            file.SaveAs(Server.MapPath(path));
                            if (i == 0)
                                mdl.Image = path.Replace("~/", "/../");
                            else if (i == 1)
                                mdl.S1Image = path.Replace("~/", "/../");
                            else if (i == 2)
                                mdl.S2Image = path.Replace("~/", "/../");
                            else 
                                mdl.S3Image = path.Replace("~/", "/../");
                        }
                    }
                }
               
                if (ModelState.IsValid)
                {
                    mdl.ID = Convert.ToInt32(Session["UserID"]);
                    BLL_Taylor obj = new BLL_Taylor();
                    obj.BLL_AddTaylor(mdl);
                    ViewBag.Message = "Taylor Added Successfully";
                    return View();
                }
                else
                    return View();
                
            }
            catch (Exception)
            {

                throw;
            }

        }

        public ActionResult AddPortfolio()
        {

            try
            {
                BLL_Taylor obj = new BLL_Taylor();
                List<MdlTaylor> mdlist = obj.BLL_ReadTaylor(Convert.ToInt32(Session["UserID"]));
                Mdl_Portfolio mdl = new Mdl_Portfolio();
                mdl.TaylorList = mdlist;
                return View(mdl);
            }
            catch (Exception)
            {

                throw;
            }

        }
        [HttpPost]
        public ActionResult AddPortfolio(Mdl_Portfolio mdl , HttpPostedFileBase file)
        {
            var allowedextention = new[] { ".jpg", ".Jpg", ".jpeg", ".png" };
            if (file != null)
            {
                var ext = Path.GetExtension(file.FileName);
                if (allowedextention.Contains(ext))
                {
                    var filename = Path.GetFileName(file.FileName);
                    var path = "~/Images/Portfolio/" + filename + ext;
                    file.SaveAs(Server.MapPath(path));
                    mdl.Image = path.Replace("~/", "/../");
                }
               
            }
            if (ModelState.IsValid)
            {
                BLL_Taylor obj = new BLL_Taylor();
                obj.BLL_AddPortfolio(mdl);
                ViewBag.Message = "Portfolio Save Successfully";
                List<MdlTaylor> mdlist = obj.BLL_ReadTaylor(Convert.ToInt32(Session["UserID"]));
                mdl.TaylorList = mdlist;
                return View(mdl);
            }
            else
                return RedirectToAction("AddPortfolio");
        }

        public ActionResult Portfolio(int ID)
        {
            Session["TaylorID"] = ID;
            BLL_Taylor obj = new BLL_Taylor();
            MdlTaylor mdl = obj.BLL_ReadSingleTaylor(ID);
            return View(mdl);
        }

        public ActionResult PortfolioPartial()
        {
            BLL_Taylor obj = new BLL_Taylor();
            List<Mdl_Portfolio> mdl = obj.BLL_ReadPortfolio(Convert.ToInt32(Session["TaylorID"]));
            return PartialView(mdl);
        }
    }
}

Pick n Buy/Views/Taylor/AddPortfolio.cshtml
@model OTM.Models.Mdl_Portfolio

@{
    ViewBag.Title = "AddPortfolio";
    Layout = "~/Views/Shared/_TaylorLayout.cshtml";
}
@if (ViewBag.Message != null)
        {
<br />
<div class="alert alert-success">
    @ViewBag.Message
</div>
        }
<div class="mx-auto"><h2 class="text-black-50">Add Portfolio</h2></div>

@using (Html.BeginForm("AddPortfolio", "Taylor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="mx-auto">
            @Html.DropDownListFor(md => md.ID, new SelectList(Model.TaylorList, "ID", "Name"), "--Select Taylor--", new { @class = "form-control", @style = "border-radius:25px;" })
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="custom-file form-inline mt-4">
            <div class="col-md-10">
                <input type="file" name="file" id="customFile" class="custom-file-input" />
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "custom-file-label", @for = "customFile" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-inline mt-4">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-2 col-md-10">
                <input type="submit" value="Enter" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Pick n Buy/Views/Taylor/AddTaylor.cshtml
@model OTM.Models.MdlTaylor

@{
    ViewBag.Title = "AddTaylor";
    Layout = "~/Views/Shared/_TaylorLayout.cshtml";
}

@if (ViewBag.Message != null)
{
    <br />
    <div class="alert alert-success">
        @ViewBag.Message
    </div>
}
@using (Html.BeginForm("AddTaylor", "Taylor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-inline mt-3">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline mt-3">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.About, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.About) })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="custom-file form-inline mt-4">
            <div class="col-md-8">
                <input type="file" name="files" id="file4" class="custom-file-input" />
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "custom-file-label", @for = "file4" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="card">
            <div class="card-header text-black-50 h3">Please Enter 3 Services that Taylor Provide</div>
            <div class="card-header-pills mx-auto text-info">i.e 3 Type of  Stitching Taylor Provide</div>
            <div class="card-body">
                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.Skill1, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.Skill1, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.Skill1) })
                        @Html.ValidationMessageFor(model => model.Skill1, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.Skill2, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.Skill2, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.Skill2) })
                        @Html.ValidationMessageFor(model => model.Skill2, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.Skill3, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.Skill3, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.Skill3) })
                        @Html.ValidationMessageFor(model => model.Skill3, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.S1Des, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.S1Des, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.S1Des) })
                        @Html.ValidationMessageFor(model => model.S1Des, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.S2Des, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.S2Des, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.S2Des) })
                        @Html.ValidationMessageFor(model => model.S2Des, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-inline mt-3">
                    @Html.LabelFor(model => model.S3Des, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.S3Des, new { @rows = 4, @class = "col-md-12", placeholder = Html.DisplayNameFor(x => x.S3Des) })
                        @Html.ValidationMessageFor(model => model.S3Des, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="custom-file form-inline mt-4">
                    <div class="col-md-8">
                        <input type="file" name="files" id="file3" class="custom-file-input" />
                        @Html.LabelFor(model => model.S1Image, htmlAttributes: new { @class = "custom-file-label", @for = "file3" })
                        @Html.ValidationMessageFor(model => model.S1Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="custom-file form-inline mt-4">
                    <div class="col-md-8">
                        <input type="file" name="files" id="file1" class="custom-file-input" />
                        @Html.LabelFor(model => model.S2Image, htmlAttributes: new { @class = "custom-file-label", @for = "file1" })
                        @Html.ValidationMessageFor(model => model.S2Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="custom-file form-inline mt-4">
                    <div class="col-md-8">
                        <input type="file" name="files" id="file2" class="custom-file-input" />
                        @Html.LabelFor(model => model.S3Image, htmlAttributes: new { @class = "custom-file-label", @for = "file2" })
                        @Html.ValidationMessageFor(model => model.S3Image, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-secondary" />
            </div>
        </div>
    </div>
}

Pick n Buy/Views/Taylor/Portfolio.cshtml
@model OTM.Models.MdlTaylor
@{
    ViewBag.Title = "Portfolio";
    Layout = "~/Views/Shared/_PortfolioLayout.cshtml";
}
<!-- slider_area_start -->
<div class="slider_area">
    <div class="single_slider  d-flex align-items-center slider_bg_1">
        <div class="shap_pattern d-none d-lg-block">
            <img src="/../images/grid.png" alt="">
        </div>
        <div class="social_links">
            <ul>
                <li><a href="#"> <i class="fab fa-facebook"></i> </a></li>
                <li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
                <li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
            </ul>
        </div>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-12">
                    <div class="slider_text text-center">
                        <h3>
                            @Model.Name
                        </h3>
                        <span>@Model.About</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider_area_end -->
<!-- service_area  -->
<div class="service_area">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section_title text-center mb-65">
                    <span>Service Provided</span>
                    <h3>
                        Build brands campaigns
                    </h3>
                    @Html.ActionLink("Chat", "Index", "Chat", null, htmlAttributes: new { @class = "display-5" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-4 col-md-4">
                <div class="single_service text-center">
                    <div class="icon">
                        <img src="@Url.Content(Model.S1Image)" alt="" width="300" height="300">
                    </div>
                    <h3>@Model.Skill1</h3>
                    <p>@Model.S3Des</p>
                </div>
            </div>
            <div class="col-xl-4 col-md-4">
                <div class="single_service text-center">
                    <div class="icon">
                        <img src="@Url.Content(Model.S2Image)" alt="" width="300" height="300">
                    </div>
                    <h3>@Model.Skill2</h3>
                    <p>@Model.S2Des</p>
                </div>
            </div>
            <div class="col-xl-4 col-md-4">
                <div class="single_service text-center">
                    <div class="icon">
                        <img src="@Url.Content(Model.S3Image)" alt="" width="300" height="300">
                    </div>
                    <h3>@Model.Skill3</h3>
                    <p>@Model.S3Des</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ service_area  -->

@Html.Action("PortfolioPartial", "Taylor")

Pick n Buy/Views/Taylor/PortfolioPartial.cshtml
@model IEnumerable<OTM.Models.Mdl_Portfolio>

<!-- portfolio_area -->
<div class="portfolio_area portfolio_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section_title white_text text-center">
                    <span>Portfolios</span>
                    <h3>
                        Some of my awesome <br>
                        stuffs here
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ portfolio_area -->
<!-- portfolio_image_area  -->
<div class="portfolio_image_area">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-xl-5 col-md-5 col-lg-4">
                    <div class="single_Portfolio">
                        <div class="portfolio_thumb">
                            <img src="@Url.Content(item.Image)" alt="">
                        </div>
                        <a href="@Url.Content(item.Image)" class="popup popup-image"></a>
                        <div class="portfolio_hover">
                            <div class="title">
                                <h5>@item.About</h5>
                            </div>
                        </div>
                    </div>
                </div>
            }
            </div>
        <div class="row">
            <div class="col-xl-12">
                <div class="more_portfolio text-center">
                    <a class="line_btn" href="#">More Folio</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ portfolio_image_area  -->

Pick n Buy/Views/Taylor/Taylor.cshtml
@model IEnumerable<OTM.Models.MdlTaylor>
@{
    ViewBag.Title = "Taylor";
    Layout = "~/Views/Shared/_TaylorLayout.cshtml";
}

<h2 class="text-secondary text-center">Products</h2>

<table class="table table-secondary table-hover">
    <tr class="row">
        <th class="col-md-3 text-center">
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th class="col-md-3 text-center">
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th class="col-md-4 text-center">
            @Html.DisplayNameFor(model => model.About)
        </th>
        <th class="col-md-2">Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="row text-primary text-center">
            <td class="col-md-3">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="col-md-3">
                <img src="@Url.Content(item.Image)" width="200" height="100" />
            </td>
            <td class="col-md-4">
                @Html.DisplayFor(modelItem => item.About)
            </td>
            <td class="col-md-2">
                @Html.ActionLink(" ", " ", " ", new { id = item.ID }, htmlAttributes: new { @class = "fa fa-edit text-warning" }) |
                @Html.ActionLink(" ", " ", " ", new { id = item.ID }, htmlAttributes: new { @class = "fa fa-trash text-danger" })
            </td>
        </tr>
    }

</table>